name: Deploy to WordPress.org

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to WordPress.org
        uses: 10up/action-wordpress-plugin-deploy@5e6c818d2a7b3cf40eb204abbfd902b473eb24d8
        with:
          slug: ${{ secrets.PLUGIN_SLUG }}
          wordpress-org-username: ${{ secrets.SVN_USERNAME }}
          wordpress-org-password: ${{ secrets.SVN_PASSWORD }}
